---
include:
  - board: eyelash_corne_left
    shield: nice_view_adapter nice_epaper
    #snippet: zmk-usb-logging    # Uncomment to log over USB.
  - board: eyelash_corne_right
    shield: nice_view_adapter nice_epaper
    #snippet: zmk-usb-logging
  # Опциональная конфигурация для nice_oled (закомментирована)
  # - board: eyelash_corne_left
  #   shield: nice_oled
  # - board: eyelash_corne_right
  #   shield: nice_oled
  - board: eyelash_corne_left
    shield: settings_reset
    #snippet: zmk-usb-logging
 
